# Generated by Django 3.1.5 on 2021-01-10 14:08

from django.db import migrations, models
import datetime

current_year = '2020/21'

def offset(day, day_t):
    if day < day_t:
        return day - day_t + 7
    elif day > day_t :
        return day - day_t
    else:
        return 0

def move_reservation(apps, schema_editor):
    Reservations = apps.get_model('schedule', 'Specialreservation')
    Event = apps.get_model('schedule', 'Event')
    Term = apps.get_model('schedule', 'Term')
    User = apps.get_model('auth', 'User')
    for reservation in Reservations.objects.filter(
            semester__year=current_year):
        new_event = Event(
            title=reservation.title,
            description='Rezerwacja stała',
            type='5',
            visible=True,
            status='1',
            author=User.objects.get(username='asm')
        )

        new_event.save()
        semester_start = reservation.semester.lectures_beginning
        semester_end = reservation.semester.lectures_ending

        off = offset(int(reservation.dayOfWeek), semester_start.weekday())
        semester_start += datetime.timedelta(days=off)
        while semester_start <= semester_end:
            new_term = Term(
                event=new_event,
                day=semester_start,
                start=reservation.start_time,
                end=reservation.end_time,
                room=reservation.classroom,
                place=reservation.title,
                ignore_conflicts=True
            )
            new_term.save()
            semester_start += datetime.timedelta(days=7)

class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0009_term_ignore_conflicts'),
    ]

    operations = [

        migrations.RemoveField(
            model_name='eventmoderationmessage',
            name='author',
        ),
        migrations.RemoveField(
            model_name='eventmoderationmessage',
            name='event',
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('0', 'Egzamin'), ('1', 'Kolokwium'), ('2', 'Wydarzenie'), ('3', 'Zajęcia'), ('5', 'Rezerwacja stała'), ('4', 'Inne')], max_length=1, verbose_name='Typ'),
        ),
        migrations.DeleteModel(
            name='EventMessage',
        ),
        migrations.DeleteModel(
            name='EventModerationMessage',
        ),
        migrations.RunPython(
            move_reservation
        )
    ]
