# Generated by Django 3.1.5 on 2021-01-22 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0009_term_ignore_conflicts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventmoderationmessage',
            name='author',
        ),
        migrations.RemoveField(
            model_name='eventmoderationmessage',
            name='event',
        ),
        migrations.DeleteModel(
            name='EventMessage',
        ),
        migrations.DeleteModel(
            name='EventModerationMessage',
        ),
    ]
