# Generated by Django 3.1.5 on 2021-01-24 10:03

from django.db import migrations, models
current_year = '2020/21'

def move_reservation(apps, schema_editor):
    Reservations = apps.get_model('schedule', 'Specialreservation')
    Event = apps.get_model('schedule', 'Event')
    reservations = Reservations.objects.all()
    for reservation in reservations:
        old_event = Event.objects.get(reservation=reservation)
        old_event.type = '5'
        old_event.save()


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0010_auto_20210122_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('0', 'Egzamin'), ('1', 'Kolokwium'), ('2', 'Wydarzenie'), ('3', 'Zajęcia'), ('5', 'Rezerwacja stała'), ('4', 'Inne')], max_length=1, verbose_name='Typ'),
        ),
        migrations.RunPython(
            move_reservation
        ),
    ]
