# Generated by Django 3.1.5 on 2021-01-24 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0010_auto_20210122_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('0', 'Egzamin'), ('1', 'Kolokwium'), ('2', 'Wydarzenie'), ('3', 'Zajęcia'), ('5', 'Rezerwacja stała'), ('4', 'Inne')], max_length=1, verbose_name='Typ'),
        ),
        migrations.AddField(
            model_name='event',
            name='semester',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='courses.semester', verbose_name='semestr'),
        ),
    ]
