# Generated by Django 3.1.5 on 2021-01-24 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0011_auto_20210124_1003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='reservation',
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(default='Tytuł', max_length=255, verbose_name='Tytuł'),
        ),
    ]
