# Generated by Django 3.1.5 on 2021-01-24 12:25

from django.db import migrations, models

def move_reservation(apps, schema_editor):
    Reservations = apps.get_model('schedule', 'Specialreservation')
    Event = apps.get_model('schedule', 'Event')
    reservations = Reservations.objects.all()
    for reservation in reservations:
        event = Event.objects.get(reservation=reservation)
        event.type = '5'
        event.semester = reservation.semester
        event.save()

class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0034_auto_20201106_2039'),
        ('schedule', '0011_auto_20210124_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(default='Tytuł', max_length=255, verbose_name='Tytuł'),
        ),
        migrations.RunPython(
            move_reservation
        ),
    ]
