# Generated by Django 3.1.5 on 2021-01-24 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0012_auto_20210124_1225'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SpecialReservation',
        ),
    ]
