# Generated by Django 3.1.5 on 2021-01-24 16:01

from django.db import migrations

def add_title(apps, schema_editor):
    Event = apps.get_model('schedule', 'Event')
    events = Event.objects.filter(type__in=['0', '1'])
    print(events)
    for event in events:
        if event.course != None:
            event.title = event.course.name
        else:
            event.title = event.description
        event.save()

class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0012_auto_20210124_1225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='reservation',
        ),
        migrations.DeleteModel(
            name='SpecialReservation',
        ),
        migrations.RunPython(
            add_title
        ),
    ]
