# Generated by Django 3.1.3 on 2020-11-06 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0033_auto_20200914_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='auto_enrollment',
            field=models.BooleanField(default=False, help_text='Blokuje zapisywanie do grupy. Zamiast tego, studenci są do niej automatycznie zapisani jeśli zapiszą się do jakiejkolwiek innej grupy z tego przedmiotu. Nie należy blokować wszystkich grup z przedmiotu ani grup, gdzie studenci powinni mieć wybór (np. jest kilka równoległych grup ćwiczeniowych).', verbose_name='grupa z auto-zapisem'),
        ),
        migrations.AlterField(
            model_name='group',
            name='extra',
            field=models.CharField(blank=True, default='', help_text="Można wpisywać tagi oddzielone przecinkami. Zostaną one wyświetlone na stronie przedmiotu. Nie ma żadnych dozwolonych tagów, ale dla wybranych tagów zostanie dodany tooltip z wyjaśnieniem: {'Q1': 'pierwsze 7 tygodni', 'Q2': 'drugie 7 tygodni', 'zaaw': 'grupa zaawansowana', 'mat': 'zajęcia na matematyce', 'english': 'grupa anglojęzyczna', 'zdalna': 'zajęcia prowadzone zdalnie', 'hybrydowa': 'zajęcia częściowo zdalne, częściowo stacjonarne'}", max_length=255, verbose_name='dodatkowe informacje'),
        ),
        migrations.AlterField(
            model_name='group',
            name='type',
            field=models.IntegerField(choices=[(1, 'wykład'), (2, 'ćwiczenia'), (3, 'pracownia'), (5, 'ćwiczenio-pracownia'), (6, 'seminarium'), (7, 'lektorat'), (8, 'WF'), (9, 'repetytorium'), (10, 'projekt'), (11, 'tutoring'), (12, 'proseminarium')], verbose_name='typ zajęć'),
        ),
    ]
