# Generated by Django 3.1.3 on 2020-11-19 22:00

from django.db import migrations


def populate_lectures_dates(apps, schema_editor):
    Semester = apps.get_model('courses', 'Semester')
    for semester in Semester.objects.all():
        if semester.lectures_beginning is None:
            semester.lectures_beginning = semester.semester_beginning
        if semester.lectures_ending is None:
            semester.lectures_ending = semester.semester_ending
        semester.save()


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0034_auto_20201106_2039'),
    ]

    operations = [
        migrations.RunPython(populate_lectures_dates),
    ]
