# Generated by Django 3.1.13 on 2021-10-22 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0035_auto_20210130_0042'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='usos_term_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Kod DZ_TERMINY w systemie USOS'),
        ),
        migrations.AlterField(
            model_name='term',
            name='usos_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='Kod DZ_TERMINY_GRUP w systemie USOS'),
        ),
    ]
