# Generated by Django 3.1.3 on 2020-11-08 17:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0035_auto_20201108_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='first_grade_semester',
            field=models.ForeignKey(blank=True, help_text='Semestr zimowy z poprzedniego roku akademickiego.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fgrade', to='courses.semester', verbose_name='Pierwszy semestr oceny'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='lectures_beginning',
            field=models.DateField(verbose_name='Dzień rozpoczęcia zajęć'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='lectures_ending',
            field=models.DateField(verbose_name='Dzień zakończenia zajęć'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='records_closing',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Czas zamknięcia zapisów'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='records_ects_limit_abolition',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Czas zniesienia limitu 35 ECTS'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='second_grade_semester',
            field=models.ForeignKey(blank=True, help_text='Semestr letni z poprzedniego roku akademickiego.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sgrade', to='courses.semester', verbose_name='Drugi semester oceny'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='year',
            field=models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(message='Format XXXX/YY', regex='\\d{4}/\\d{2}')], verbose_name='rok akademicki'),
        ),
    ]
