# Generated by Django 3.1.3 on 2020-11-19 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0035_populate_lectures_dates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='first_grade_semester',
            field=models.ForeignKey(blank=True, help_text='Semestr zimowy z poprzedniego roku akademickiego.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fgrade', to='courses.semester', verbose_name='Pierwszy semestr oceny'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='records_ects_limit_abolition',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Czas zniesienia limitu 35 ECTS'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='second_grade_semester',
            field=models.ForeignKey(blank=True, help_text='Semestr letni z poprzedniego roku akademickiego.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sgrade', to='courses.semester', verbose_name='Drugi semester oceny'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='year',
            field=models.CharField(default='0', help_text='Format: XXXX/YY', max_length=7, verbose_name='rok akademicki'),
        ),
    ]
