# Generated by Django 3.1.3 on 2020-11-26 21:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0036_auto_20201119_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='lectures_beginning',
            field=models.DateField(verbose_name='Dzień rozpoczęcia zajęć'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='lectures_ending',
            field=models.DateField(verbose_name='Dzień zakończenia zajęć'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='records_closing',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Czas zamknięcia zapisów'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='semester_beginning',
            field=models.DateField(blank=True, null=True, verbose_name='Data rozpoczęcia semestru'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='semester_ending',
            field=models.DateField(blank=True, null=True, verbose_name='Data zakończenia semestru'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='year',
            field=models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(message='Format XXXX/YY', regex='\\d{4}/\\d{2}')], verbose_name='rok akademicki'),
        ),
    ]
