# Generated by Django 3.1.3 on 2020-11-08 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0036_auto_20201108_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='semester_beginning',
            field=models.DateField(blank=True, null=True, verbose_name='Data rozpoczęcia semestru'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='semester_ending',
            field=models.DateField(blank=True, null=True, verbose_name='Data zakończenia semestru'),
        ),
    ]
