# Generated by Django 3.1.2 on 2020-10-29 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20200504_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='priority',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Ukryte'), (1, 'Niskie'), (2, 'Normalne'), (3, 'Wysokie')], default=2, help_text='\n            <dl>\n            <dt>Ukryte</dt>\n            <dd>Wiadomość nie zostanie opublikowana;</dd>\n            <dt>Niskie</dt>\n            <dd>Wiadomość zostanie opublikowana na stronie, ale powiadomienia\n            nie będą wysłane;\n            <dt>Normalne</dt>\n            <dd>Powiadomienia będą wysłane zgodnie z preferencjami użytkowników</dd>\n            <dt>Wysokie</dt>\n            <dd>Powiadomienia otrzymają wszyscy aktywni studenci niezależnie od\n            swoich preferencji.</dd>\n            <dl>\n            <b>Uwaga:</b> Powiadomienia są wysyłane tylko dla nowych ogłoszeń,\n            nie dla zmodyfikowanych.\n        ', verbose_name='priorytet'),
        ),
    ]
