# Generated by Django 3.1.2 on 2020-10-29 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0008_auto_20200129_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schema',
            name='questions',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='submission',
            name='answers',
            field=models.JSONField(default=dict),
        ),
    ]
