# Generated by Django 3.1.13 on 2021-12-12 16:00

import apps.theses.validators
from django.db import migrations, models

def set_my_defaults(apps, schema_editor):
    theses = apps.get_model('theses', 'thesis')
    for thesis in theses.objects.all().iterator():
        thesis.max_number_of_students = thesis.students.count() if thesis.students.count() > 0 else 1
        thesis.save()

# def reverse_func(apps, schema_editor):
#     pass  # code for reverting migration, if any

class Migration(migrations.Migration):

    dependencies = [
        ('theses', '0005_auto_20201106_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='thesis',
            name='max_number_of_students',
            field=models.SmallIntegerField(blank=True, default=None, null=True, validators=[apps.theses.validators.validate_max_number_of_students]),
        ),
        migrations.RunPython(set_my_defaults, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='thesis',
            name='max_number_of_students',
            field=models.SmallIntegerField(default=1, validators=[apps.theses.validators.validate_max_number_of_students]),
        ),
    ]
