# Generated by Django 3.1.5 on 2021-02-12 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_auto_20201010_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpreferencesstudent',
            name='terms_conflict',
            field=models.BooleanField(default=True, verbose_name='Nowa wiadomość, konflikt terminów w rezerwacji sal'),
        ),
    ]
