# Generated by Django 3.1.3 on 2020-11-06 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0010_auto_20190822_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='status',
            field=models.IntegerField(choices=[(0, 'Queued'), (1, 'Enrolled'), (2, 'Removed')]),
        ),
    ]
