# Generated by Django 3.1.3 on 2020-11-06 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0006_auto_20190804_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferencesquestion',
            name='class_type',
            field=models.CharField(choices=[(1, 'wykład'), (2, 'ćwiczenia'), (3, 'pracownia'), (5, 'ćwiczenio-pracownia'), (6, 'seminarium'), (7, 'lektorat'), (8, 'WF'), (9, 'repetytorium'), (10, 'projekt'), (11, 'tutoring'), (12, 'proseminarium')], max_length=2, verbose_name='typ zajęć'),
        ),
    ]
