# Generated by Django 3.1.2 on 2020-10-29 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_auto_20200326_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldataconsent',
            name='granted',
            field=models.BooleanField(null=True, verbose_name='zgoda udzielona'),
        ),
    ]
