# Generated by Django 3.1.14 on 2022-01-17 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import gdstorage.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Defect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nazwa')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_modification', models.DateTimeField(auto_now_add=True)),
                ('place', models.CharField(max_length=255, verbose_name='Miejsce')),
                ('description', models.TextField(blank=True, verbose_name='Opis usterki')),
                ('state', models.PositiveSmallIntegerField(choices=[(0, 'Zgłoszone'), (1, 'Nie da się'), (2, 'Dłuższy problem'), (3, 'Zrobione')], default=0, verbose_name='Stan')),
                ('information_from_repairer', models.TextField(blank=True, verbose_name='Informacja od serwisanta')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(storage=gdstorage.storage.GoogleDriveStorage(), upload_to='defect')),
                ('defect', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='defect.defect')),
            ],
        ),
    ]
