# Generated by Django 3.1.13 on 2021-11-21 23:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Defect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nazwa')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_modification', models.DateTimeField(auto_now_add=True)),
                ('place', models.CharField(max_length=255, verbose_name='Miejsce')),
                ('description', models.TextField(blank=True, verbose_name='Opis usterki')),
                ('state', models.PositiveSmallIntegerField(choices=[(0, 'Stworzone'), (1, 'Nie da się'), (2, 'Dłuższy problem'), (3, 'Zrobione')], default=0, verbose_name='Stan')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
