# Generated by Django 3.1.13 on 2021-11-07 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('image_manager', '0001_initial'),
        ('defect', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefectImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='defect.defect')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='image_manager.image')),
            ],
        ),
    ]
