# Generated by Django 3.1.13 on 2021-11-07 14:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('defect', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='defect',
            old_name='date',
            new_name='creation_date',
        ),
        migrations.RemoveField(
            model_name='defect',
            name='title',
        ),
        migrations.AddField(
            model_name='defect',
            name='last_modification',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='defect',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name='Nazwa'),
            preserve_default=False,
        ),
    ]
